### ISSUE TITLE
Extension Integration: Extension Management

### ISSUE THREAD

**Issue by bryphe** [onivim/oni2#1018]
This issue tracks the _managing_ of extensions, including:

- Install / Uninstall

To start, we'll be integrating with the ~~VSCode extension gallery~~(http://open-vsx.org/) to pull and query for extensions. However, as we support some VimL extensions, we'll be pulling in data from other places (for example, vim-awesome looks like it has a nice API for discovery: https://vimawesome.com/) - so we should keep in mind support for multiple extension 'sources'.

Right now, we load all extensions in the user's `.config/oni2/extensions` folder - so you can manually extract VSCode vsix extensions and bring them over. However, this is not a convenient method for installation.

__Part 1: Initial Management via CLI:__
- [x] Add a `--list-extensions` command that will display the current set of installed extensions
- [x] Add a `--query-extension <filter>` that will search for an extension by name and provide metadata
- [x] Add an `--install-extension <path>` command that will download the extension specified by `<id>` and unpack the VSIX into the `./config/oni2/extensions` folder.
- [x] Add an `--install-extension <id>` command that will download the extension specified by `<id>` and unpack the VSIX into the `./config/oni2/extensions` folder.
- [x] Add an `--uninstall-extension <id>` command that will delete the extension specified by `<id>` 

Unfortunately, we don't have a cross-platform Reason API for working with files that works on Windows (yet) - so we'll fallback to using some node integration scripts for the download and unpacking. 

__Part 2: UI Management:__
Once we have the core primitives for install / uninstall, we can start to expose this in the UI.
- [x] Add an option in the command palette to 'Install extensions...'. When this command is used, we will open a new menu that will query the extension API, filter results, and allow users to install an extension.
- [x] Add a special notification that shows progress while installing and success / failure status.
- [x] Add a sidebar pane to show the list of currently installed extensions.

__Part 3: Enable / Disable Extensions:__
- [ ] Expose a UI entry point to enable / disable extensions

__Part 4: Auto-update:__
- [x] Check updates for extensions
- [x] Prompt user for updates

__EDIT:__ Unfortunately, the VSCode marketplace prevents us from being able to install extensions - they have clear language that extensions downloaded from their marketplace may only be used with VSCode-family products. However, this is an open extension marketplace for VSCode compatible editors: http://open-vsx.org/ - we'll start integrating with that.

**Comment by thomas-haslwanter** [comment]
Just wanted to let you know that on my system, the command
`oni2 --uninstall-extension
`
gives the result
`Not implemented yet`

I have older python extensions that I would like to get rid off, so that I can try out oni2 with the current one (The older ones don't seem to do anything)

**Comment by tuananh** [comment]
i tried to install a theme and it fails with 

```
oni2 --install-extension github.github-vscode-the
Failed to install extension: github.github-vscode-theme
```

**Comment by glennsl** [comment]
@tuananh Installing by id directly from the marketplace isn't supported, since Microsoft does not allow it, as explained in the OP:

> Unfortunately, the VSCode marketplace prevents us from being able to install extensions - they have clear language that extensions downloaded from their marketplace may only be used with VSCode-family products. 

 You have to download the `.vsix` file yourself and install that instead. See https://onivim.github.io/docs/configuration/extensions#installing-extensions

**Comment by tuananh** [comment]
> @tuananh Installing by id directly from the marketplace isn't supported, since Microsoft does not allow it, as explained in the OP:
> 
> > Unfortunately, the VSCode marketplace prevents us from being able to install extensions - they have clear language that extensions downloaded from their marketplace may only be used with VSCode-family products.
> 
> You have to download the `.vsix` file yourself and install that instead. See https://onivim.github.io/docs/configuration/extensions#installing-extensions

does this mean this feature will be dropped ?

>  Add an --install-extension <id> command that will download the extension specified by <id> and unpack the VSIX into the ./config/oni2/extensions folder.

**Comment by glennsl** [comment]
No, we can use http://open-vsx.org/ instead, which is an open extension marketplace. Not quite as good, of course, as it'll only work for extensions that have been published there as well, but it should have most of the popular ones at least. (This is also explained in the OP, btw.)
